framework:
    messenger:

        transports:
            topic_producer:
                dsn: '%env(KAFKA_DSN)%'
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: '%env(KAFKA_TOPIC)%'
                    metadata.broker.list: '%env(KAFKA_BROKERS)%'
#                    topic_conf:
#                        retention.ms: '-1'


            topic_consumer:
                dsn: '%env(KAFKA_DSN)%'
                options:
                    commitAsync: true
                    receiveTimeout: 10000
                    topic:
                        name: '%env(KAFKA_TOPIC)%'
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'my-group-id'
                    topic_conf:
                        auto.offset.reset: 'earliest'

            slurping_consumer:
                dsn: '%env(KAFKA_DSN)%'
                options:
                    commitAsync: true
                    receiveTimeout: 3000
                    topic:
                        name: '%env(KAFKA_TOPIC)%'
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'slurping-group-id'
                    topic_conf:
                        auto.offset.reset: 'earliest'
#                        log.cleanup.policy = [compact]
#                        log.retention.bytes = -1
#                        log.retention.ms = -1

        routing:
            'App\Message\DoSomething': topic_producer

#        serializer:
#            default_serializer: messenger.transport.symfony_serializer
