version: '3.9'

services:
  php:
    build:
      context: php
      args:
          - APP_USER_ID
    container_name: ${COMPOSE_PROJECT_NAME}-php
    restart: on-failure
    user: ${APP_USER_ID}:${APP_GROUP_ID}
    volumes:
      - ../:/app/
      - ./php/php.ini:/usr/local/etc/php/conf.d/app-overrides.ini
      - appuser_home:/home/appuser
      - ~/.ssh:/home/appuser/.ssh
    environment:
      - PHP_IDE_CONFIG
    working_dir: /app
    tty: true
    networks:
        devapp:
    extra_hosts:
        - host.docker.internal:host-gateway

  go:
    build:
      context: go
      args:
        - APP_USER_ID
    container_name: ${COMPOSE_PROJECT_NAME}-go
    restart: on-failure
    tty: true
    volumes:
      - ../:/go/src/app
      - gopkg:/go/pkg
      - gobin:/go/bin
    networks:
      devapp:

  kafka:
    build:
      context: kafka
    container_name: ${COMPOSE_PROJECT_NAME}-kafka
    restart: on-failure
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://kafka:9092,PLAINTEXT://kafka:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    networks:
      devapp:

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ${COMPOSE_PROJECT_NAME}-kafka-ui
    restart: on-failure
    depends_on:
      - kafka
      - schema-registry
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    ports:
      - 8080:8080
    volumes:
      - ./kafka-ui/config.yaml:/etc/kafkaui/dynamic_config.yaml
    networks:
      devapp:

  schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: ${COMPOSE_PROJECT_NAME}-schema-registry
    restart: on-failure
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:19092'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8085'
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'
    networks:
      devapp:

networks:
  devapp:
    name: devapp

volumes:
  appuser_home:
    name: ${COMPOSE_PROJECT_NAME}-appuser-home
  kafka_data:
    name: ${COMPOSE_PROJECT_NAME}-kafka-data
  gopkg:
    name: ${COMPOSE_PROJECT_NAME}-gopkg
  gobin:
    name: ${COMPOSE_PROJECT_NAME}-gobin
